import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import os from "os";
import path from "path";
import fs from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the GitHub repository
https://github.com/minddock/obsidian-minddock
*/
`;

const prod = process.argv[2] === "production";

// Schrijf output naar os.tmpdir() om Controlled Folder Access te omzeilen.
// Na het builden wordt het bestand gekopieerd naar de plugin-directory.
const tmpOutDir = path.join(os.tmpdir(), "minddock-plugin-build");
const tmpOutFile = path.join(tmpOutDir, "main.js");
const finalOutFile = "main.js";

if (!fs.existsSync(tmpOutDir)) {
  fs.mkdirSync(tmpOutDir, { recursive: true });
}

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: tmpOutFile,
});

if (prod) {
  await context.rebuild();

  // Kopieer van tmpdir naar plugin-directory via Node.js fs.copyFile
  // (werkt omdat VS Code / de build-omgeving schrijfrechten heeft)
  try {
    fs.copyFileSync(tmpOutFile, finalOutFile);
    console.log(`✅ main.js gekopieerd van ${tmpOutFile} naar ${finalOutFile}`);
  } catch (copyErr) {
    // Als copyFile ook mislukt (Controlled Folder Access), geef een duidelijke instructie
    console.error(`❌ Kon main.js niet kopiëren naar ${finalOutFile}: ${copyErr.message}`);
    console.log(`\n💡 Kopieer handmatig:\n   ${tmpOutFile}\n   → ${path.resolve(finalOutFile)}`);
    console.log(`\n   Of voeg Node.js (${process.execPath}) toe als toegestane app`);
    console.log(`   in Windows Beveiliging → Controlled Folder Access → Toegestane apps\n`);
  }

  process.exit(0);
} else {
  // Watch mode: kopieer na elke rebuild
  context.watch().then(() => {
    console.log("👀 Watching for changes...");
  });
}
